version: "2.0"

services:
  pgadmin:
    image: dpage/pgadmin4:5
    restart: always
    ports:
      - 8000:80
    links:
      - db:db
    environment:
      - PGADMIN_DEFAULT_EMAIL=john@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  db:
    image: postgres:13.2
    restart: always
    volumes:
      - db:/var/lib/data
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./client/dist:/var/www
      - ./client/nginx/conf.d/:/etc/nginx/conf.d/

  server:
    image: app_server:latest
    build:
      context: ./server
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  db:
    driver: local
