version: "2.0"

services:
  pgadmin:
    image: dpage/pgadmin4:5
    restart: always
    ports:
      - 8000:80
    links:
      - db:db
    environment:
      - PGADMIN_DEFAULT_EMAIL=john@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  db:
    image: postgres:13.2
    restart: always
    volumes:
      - db:/var/lib/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  db:
    driver: local
